PRIMER_PRODUCT_SIZE_RANGE: 90-140
PRIMER_NUM_RETURN: 10
PRIMER_MAX_END_STABILITY: 9
PRIMER_MIN_SIZE: 20
PRIMER_OPT_SIZE: 25
PRIMER_MAX_SIZE: 28
PRIMER_MIN_TM: 60
PRIMER_OPT_TM: 64
PRIMER_MAX_TM: 70
PRIMER_MAX_DIFF_TM: 2
PRIMER_PRODUCT_OPT_TM: 50
PRIMER_MIN_GC: 35
PRIMER_OPT_GC_PERCENT: 65
PRIMER_MAX_GC: 80
PRIMER_SELF_ANY: 4
PRIMER_MAX_POLY_X: 3